# Generated by Django 4.1 on 2022-08-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=30)),
                ('departmentid', models.CharField(max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('employeeid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employeename', models.CharField(max_length=20)),
                ('departmentid', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['-updated', '-created'],
                'managed': True,
            },
        ),
    ]
